import 'package:flutter_test/flutter_test.dart';
import 'package:magic_cli/src/helpers/console_style.dart';

/// Safety-net tests for [ConsoleStyle] public API.
///
/// Verifies ANSI formatting, banner layout, table rendering,
/// and every public static method's return-value contract.
void main() {
  // ANSI escape sequences used throughout assertions.
  const String green = '\x1B[32m';
  const String red = '\x1B[31m';
  const String yellow = '\x1B[33m';
  const String blue = '\x1B[34m';
  const String cyan = '\x1B[36m';
  const String bold = '\x1B[1m';
  const String dim = '\x1B[2m';
  const String reset = '\x1B[0m';

  group('ConsoleStyle — ANSI constants', () {
    test('green constant equals \\x1B[32m', () {
      expect(ConsoleStyle.green, equals('\x1B[32m'));
    });

    test('red constant equals \\x1B[31m', () {
      expect(ConsoleStyle.red, equals('\x1B[31m'));
    });

    test('yellow constant equals \\x1B[33m', () {
      expect(ConsoleStyle.yellow, equals('\x1B[33m'));
    });

    test('blue constant equals \\x1B[34m', () {
      expect(ConsoleStyle.blue, equals('\x1B[34m'));
    });

    test('cyan constant equals \\x1B[36m', () {
      expect(ConsoleStyle.cyan, equals('\x1B[36m'));
    });

    test('magenta constant equals \\x1B[35m', () {
      expect(ConsoleStyle.magenta, equals('\x1B[35m'));
    });

    test('white constant equals \\x1B[37m', () {
      expect(ConsoleStyle.white, equals('\x1B[37m'));
    });

    test('bold constant equals \\x1B[1m', () {
      expect(ConsoleStyle.bold, equals('\x1B[1m'));
    });

    test('dim constant equals \\x1B[2m', () {
      expect(ConsoleStyle.dim, equals('\x1B[2m'));
    });

    test('reset constant equals \\x1B[0m', () {
      expect(ConsoleStyle.reset, equals('\x1B[0m'));
    });
  });

  group('ConsoleStyle.success()', () {
    test('wraps message with green checkmark and reset', () {
      final result = ConsoleStyle.success('Done');
      expect(result, equals('${green}✓$reset Done'));
    });

    test('preserves the message content verbatim', () {
      final result = ConsoleStyle.success('Migration completed successfully');
      expect(result, contains('Migration completed successfully'));
    });

    test('starts with the green ANSI code', () {
      expect(ConsoleStyle.success('x'), startsWith(green));
    });

    test('ends with the message after the reset sequence', () {
      final result = ConsoleStyle.success('hello');
      expect(result, endsWith('hello'));
    });
  });

  group('ConsoleStyle.error()', () {
    test('wraps message with red X and reset', () {
      final result = ConsoleStyle.error('Failed');
      expect(result, equals('${red}✗$reset Failed'));
    });

    test('preserves the message content verbatim', () {
      final result = ConsoleStyle.error('File not found: path/to/file');
      expect(result, contains('File not found: path/to/file'));
    });

    test('starts with the red ANSI code', () {
      expect(ConsoleStyle.error('x'), startsWith(red));
    });
  });

  group('ConsoleStyle.info()', () {
    test('wraps message with blue info symbol and reset', () {
      final result = ConsoleStyle.info('Information');
      expect(result, equals('$blue ℹ$reset Information'));
    });

    test('preserves message content', () {
      final result = ConsoleStyle.info('Processing 42 items');
      expect(result, contains('Processing 42 items'));
    });

    test('starts with blue ANSI code', () {
      expect(ConsoleStyle.info('x'), startsWith(blue));
    });
  });

  group('ConsoleStyle.warning()', () {
    test('wraps message with yellow warning symbol and reset', () {
      final result = ConsoleStyle.warning('Danger');
      expect(result, equals('${yellow}⚠$reset Danger'));
    });

    test('preserves message content', () {
      final result = ConsoleStyle.warning('Deprecated API usage');
      expect(result, contains('Deprecated API usage'));
    });

    test('starts with yellow ANSI code', () {
      expect(ConsoleStyle.warning('x'), startsWith(yellow));
    });
  });

  group('ConsoleStyle.comment()', () {
    test('wraps message with dim and reset', () {
      final result = ConsoleStyle.comment('Note');
      expect(result, equals('${dim}Note$reset'));
    });

    test('preserves the full message', () {
      final result = ConsoleStyle.comment('// Generated by magic_cli');
      expect(result, contains('// Generated by magic_cli'));
    });

    test('starts with dim ANSI code', () {
      expect(ConsoleStyle.comment('x'), startsWith(dim));
    });

    test('ends with reset sequence', () {
      expect(ConsoleStyle.comment('x'), endsWith(reset));
    });
  });

  group('ConsoleStyle.step()', () {
    test('formats step counter as [current/total] description', () {
      final result = ConsoleStyle.step(3, 5, 'Installing packages');
      expect(result, equals('${cyan}[3/5]$reset Installing packages'));
    });

    test('preserves description text', () {
      final result = ConsoleStyle.step(1, 1, 'Finishing up');
      expect(result, contains('Finishing up'));
    });

    test('uses cyan for the bracket portion', () {
      expect(ConsoleStyle.step(1, 10, 'go'), startsWith(cyan));
    });

    test('step 1 of 1 shows [1/1]', () {
      expect(ConsoleStyle.step(1, 1, 'done'), contains('[1/1]'));
    });

    test('larger numbers are formatted correctly', () {
      final result = ConsoleStyle.step(10, 100, 'batch');
      expect(result, contains('[10/100]'));
    });
  });

  group('ConsoleStyle.line()', () {
    test('returns 50 default characters by default', () {
      final result = ConsoleStyle.line();
      expect(result.length, equals(50));
    });

    test('default character is ─', () {
      final result = ConsoleStyle.line();
      expect(result, equals('─' * 50));
    });

    test('custom length is respected', () {
      final result = ConsoleStyle.line(length: 20);
      expect(result.length, equals(20));
    });

    test('custom character is repeated', () {
      final result = ConsoleStyle.line(char: '=', length: 10);
      expect(result, equals('=' * 10));
    });

    test('length zero returns empty string', () {
      expect(ConsoleStyle.line(length: 0), equals(''));
    });

    test('length 1 returns single character', () {
      expect(ConsoleStyle.line(char: '-', length: 1), equals('-'));
    });
  });

  group('ConsoleStyle.newLine()', () {
    test('returns empty string', () {
      expect(ConsoleStyle.newLine(), equals(''));
    });
  });

  group('ConsoleStyle.header()', () {
    test('wraps title with bold and cyan codes', () {
      final result = ConsoleStyle.header('Configuration');
      expect(result, equals('$bold${cyan}Configuration$reset'));
    });

    test('starts with bold ANSI code', () {
      expect(ConsoleStyle.header('Title'), startsWith(bold));
    });

    test('ends with reset sequence', () {
      expect(ConsoleStyle.header('Title'), endsWith(reset));
    });

    test('preserves title text', () {
      final result = ConsoleStyle.header('Database Settings');
      expect(result, contains('Database Settings'));
    });
  });

  group('ConsoleStyle.banner()', () {
    test('contains the title', () {
      final result = ConsoleStyle.banner('Magic CLI', '1.0.0');
      expect(result, contains('Magic CLI'));
    });

    test('contains the version', () {
      final result = ConsoleStyle.banner('Magic CLI', '1.0.0');
      expect(result, contains('1.0.0'));
    });

    test('contains box-drawing characters ╔ ╚ ║', () {
      final result = ConsoleStyle.banner('Magic CLI', '1.0.0');
      expect(result, contains('╔'));
      expect(result, contains('╚'));
      expect(result, contains('║'));
    });

    test('starts with green ANSI code', () {
      expect(ConsoleStyle.banner('T', '1'), startsWith(green));
    });

    test('ends with reset ANSI code', () {
      expect(ConsoleStyle.banner('T', '1'), endsWith(reset));
    });

    test('spans three lines (top + content + bottom)', () {
      final result = ConsoleStyle.banner('CLI', '2.0');
      // Strip ANSI and count lines
      final cleaned = result.replaceAll(RegExp(r'\x1B\[[0-9;]*m'), '');
      expect(cleaned.split('\n').length, equals(3));
    });

    test('title and version separated by v', () {
      final result = ConsoleStyle.banner('Magic CLI', '2.5.0');
      expect(result, contains('Magic CLI v2.5.0'));
    });
  });

  group('ConsoleStyle.table()', () {
    test('returns empty string when headers are empty', () {
      final result = ConsoleStyle.table([], []);
      expect(result, equals(''));
    });

    test('contains each header in output', () {
      final result = ConsoleStyle.table(
        ['Name', 'Status'],
        [],
      );
      expect(result, contains('Name'));
      expect(result, contains('Status'));
    });

    test('contains row values in output', () {
      final result = ConsoleStyle.table(
        ['Name', 'Status'],
        [
          ['Alice', 'Active'],
          ['Bob', 'Inactive'],
        ],
      );
      expect(result, contains('Alice'));
      expect(result, contains('Active'));
      expect(result, contains('Bob'));
      expect(result, contains('Inactive'));
    });

    test('contains separator line of ─ characters', () {
      final result = ConsoleStyle.table(
        ['Col'],
        [
          ['val']
        ],
      );
      expect(result, contains('─'));
    });

    test('wraps headers in bold', () {
      final result = ConsoleStyle.table(
        ['Header'],
        [],
      );
      expect(result, contains(bold));
      expect(result, contains(reset));
    });

    test('empty rows list still produces header and separator', () {
      final result = ConsoleStyle.table(
        ['A', 'B'],
        [],
      );
      // Header + separator should be present; no data rows
      expect(result, isNotEmpty);
      expect(result, contains('A'));
    });

    test('handles single column table', () {
      final result = ConsoleStyle.table(
        ['Name'],
        [
          ['Alice'],
          ['Bob'],
        ],
      );
      expect(result, contains('Alice'));
      expect(result, contains('Bob'));
    });

    test('columns are padded to the widest value width', () {
      // 'LongHeaderName' is wider than 'Bob' — Bob should be padded.
      final result = ConsoleStyle.table(
        ['LongHeaderName', 'B'],
        [
          ['Bob', 'X'],
        ],
      );
      // Bob should be padded to at least LongHeaderName.length
      final plainResult = result.replaceAll(RegExp(r'\x1B\[[0-9;]*m'), '');
      // Row should contain spaces after Bob
      expect(plainResult, contains('Bob'));
    });
  });

  group('ConsoleStyle.keyValue()', () {
    test('contains the key and value', () {
      final result = ConsoleStyle.keyValue('Name', 'John Doe');
      expect(result, contains('Name'));
      expect(result, contains('John Doe'));
    });

    test('wraps key in cyan', () {
      final result = ConsoleStyle.keyValue('Status', 'Active');
      expect(result, contains(cyan));
      expect(result, contains(reset));
    });

    test('default key width is 20 characters', () {
      // Key is padded to 20 chars inside cyan escape codes
      final result = ConsoleStyle.keyValue('Short', 'val');
      // After ANSI stripping, 'Short' should be padded to 20
      final plainResult = result.replaceAll(RegExp(r'\x1B\[[0-9;]*m'), '');
      expect(plainResult.startsWith('Short'.padRight(20)), isTrue);
    });

    test('custom keyWidth is respected', () {
      final result = ConsoleStyle.keyValue('Key', 'val', keyWidth: 10);
      final plainResult = result.replaceAll(RegExp(r'\x1B\[[0-9;]*m'), '');
      expect(plainResult.startsWith('Key'.padRight(10)), isTrue);
    });

    test('value appears after padded key', () {
      final result = ConsoleStyle.keyValue('Name', 'Alice');
      expect(result, contains('Alice'));
    });
  });
}
